#!/bin/bash
#
# ci/scripts/create-release-and-deploy
#
# Script for generating Github release / tag assets
# and managing release notes for a BOSH Release pipeline
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

## no need in bosh v2, just use cli to log in
#header "Setting up ~/.bosh_config..."
#cat > ~/.bosh_config << EOF
#---
#aliases:
#  target:
#    bosh-lite: ${BOSH_LITE_TARGET}
#auth:
#  ${BOSH_LITE_TARGET}:
#    username: ${BOSH_LITE_USERNAME}
#    password: ${BOSH_LITE_PASSWORD}
#EOF

set -e
cd ${REPO_ROOT}
header "Pulling in any git submodules..."
git submodule update --init --recursive --force

header "Cleaning up from any previous deployments..."
#bosh -e ${BOSH_TARGET} login --client=${BOSH_USERNAME} --client-secret=${BOSH_PASSWORD} --ca-cert=${BOSH_CA_CERT}
export BOSH_CA_CERT=${BOSH_CA_CERT}
export BOSH_CLIENT=${BOSH_USERNAME}
export BOSH_CLIENT_SECRET=${BOSH_PASSWORD}
bosh -n -e ${BOSH_TARGET} -d ${BOSH_DEPLOYMENT} deld --force || echo "continuing on..."

header "Creating candidate BOSH release..."
bosh -n create-release --force --version 
header "Uploading BOSH release..."
bosh -n -e ${BOSH_TARGET} upload-release --rebase || echo "Continuing..."

header "Deploying to BOSH..."
#./templates/make_manifest warden
bosh -n -e ${BOSH_TARGET} -d ${BOSH_DEPLOYMENT} d ./manifests/deployment.yml

## maybe later?
#if [[ -n ${TEST_ERRAND} ]]; then
#  header "Running '${TEST_ERRAND}' validation errand"
#  bosh -n run errand ${TEST_ERRAND}
#fi

header "Cleaning up..."
bosh -n -e ${BOSH_TARGET} -d ${BOSH_DEPLOYMENT} deld --force || echo "continuing on..."
bosh -n -e ${BOSH_TARGET} clean-up --client=${BOSH_USERNAME} || echo "continuing on..."

echo
echo "SUCCESS"
exit 0

